# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: news.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnews.proto\x12\x04news\"\x07\n\x05\x45mpty\"\x88\x01\n\x04News\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0f\n\x07summary\x18\x05 \x01(\t\x12\x11\n\timage_url\x18\x06 \x01(\t\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\"%\n\x08NewsList\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.news.News\"\x1b\n\rNewsIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"u\n\x11NewsCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\"\xd5\x01\n\x11NewsUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07summary\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x16\n\timage_url\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x0c\n\x04tags\x18\x07 \x03(\tB\x08\n\x06_titleB\t\n\x07_authorB\n\n\x08_contentB\n\n\x08_summaryB\x0c\n\n_image_url\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb4\x02\n\x0bNewsService\x12\'\n\x08ListNews\x12\x0b.news.Empty\x1a\x0e.news.NewsList\x12*\n\x07GetNews\x12\x13.news.NewsIdRequest\x1a\n.news.News\x12\x31\n\nCreateNews\x12\x17.news.NewsCreateRequest\x1a\n.news.News\x12\x31\n\nUpdateNews\x12\x17.news.NewsUpdateRequest\x1a\n.news.News\x12\x37\n\nDeleteNews\x12\x13.news.NewsIdRequest\x1a\x14.news.DeleteResponse\x12\x31\n\nSearchNews\x12\x13.news.SearchRequest\x1a\x0e.news.NewsListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_NEWS']._serialized_start=30
  _globals['_NEWS']._serialized_end=166
  _globals['_NEWSLIST']._serialized_start=168
  _globals['_NEWSLIST']._serialized_end=205
  _globals['_NEWSIDREQUEST']._serialized_start=207
  _globals['_NEWSIDREQUEST']._serialized_end=234
  _globals['_NEWSCREATEREQUEST']._serialized_start=236
  _globals['_NEWSCREATEREQUEST']._serialized_end=353
  _globals['_NEWSUPDATEREQUEST']._serialized_start=356
  _globals['_NEWSUPDATEREQUEST']._serialized_end=569
  _globals['_SEARCHREQUEST']._serialized_start=571
  _globals['_SEARCHREQUEST']._serialized_end=601
  _globals['_DELETERESPONSE']._serialized_start=603
  _globals['_DELETERESPONSE']._serialized_end=653
  _globals['_NEWSSERVICE']._serialized_start=656
  _globals['_NEWSSERVICE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
