# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc.news_pb2 as news__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in news_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NewsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNews = channel.unary_unary(
                '/news.NewsService/ListNews',
                request_serializer=news__pb2.Empty.SerializeToString,
                response_deserializer=news__pb2.NewsList.FromString,
                _registered_method=True)
        self.GetNews = channel.unary_unary(
                '/news.NewsService/GetNews',
                request_serializer=news__pb2.NewsIdRequest.SerializeToString,
                response_deserializer=news__pb2.News.FromString,
                _registered_method=True)
        self.CreateNews = channel.unary_unary(
                '/news.NewsService/CreateNews',
                request_serializer=news__pb2.NewsCreateRequest.SerializeToString,
                response_deserializer=news__pb2.News.FromString,
                _registered_method=True)
        self.UpdateNews = channel.unary_unary(
                '/news.NewsService/UpdateNews',
                request_serializer=news__pb2.NewsUpdateRequest.SerializeToString,
                response_deserializer=news__pb2.News.FromString,
                _registered_method=True)
        self.DeleteNews = channel.unary_unary(
                '/news.NewsService/DeleteNews',
                request_serializer=news__pb2.NewsIdRequest.SerializeToString,
                response_deserializer=news__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.SearchNews = channel.unary_unary(
                '/news.NewsService/SearchNews',
                request_serializer=news__pb2.SearchRequest.SerializeToString,
                response_deserializer=news__pb2.NewsList.FromString,
                _registered_method=True)


class NewsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NewsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNews,
                    request_deserializer=news__pb2.Empty.FromString,
                    response_serializer=news__pb2.NewsList.SerializeToString,
            ),
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=news__pb2.NewsIdRequest.FromString,
                    response_serializer=news__pb2.News.SerializeToString,
            ),
            'CreateNews': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNews,
                    request_deserializer=news__pb2.NewsCreateRequest.FromString,
                    response_serializer=news__pb2.News.SerializeToString,
            ),
            'UpdateNews': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNews,
                    request_deserializer=news__pb2.NewsUpdateRequest.FromString,
                    response_serializer=news__pb2.News.SerializeToString,
            ),
            'DeleteNews': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNews,
                    request_deserializer=news__pb2.NewsIdRequest.FromString,
                    response_serializer=news__pb2.DeleteResponse.SerializeToString,
            ),
            'SearchNews': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNews,
                    request_deserializer=news__pb2.SearchRequest.FromString,
                    response_serializer=news__pb2.NewsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'news.NewsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('news.NewsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NewsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/ListNews',
            news__pb2.Empty.SerializeToString,
            news__pb2.NewsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/GetNews',
            news__pb2.NewsIdRequest.SerializeToString,
            news__pb2.News.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/CreateNews',
            news__pb2.NewsCreateRequest.SerializeToString,
            news__pb2.News.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/UpdateNews',
            news__pb2.NewsUpdateRequest.SerializeToString,
            news__pb2.News.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/DeleteNews',
            news__pb2.NewsIdRequest.SerializeToString,
            news__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/news.NewsService/SearchNews',
            news__pb2.SearchRequest.SerializeToString,
            news__pb2.NewsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
